### ISSUE TITLE
When can we expect the PR# 2025 to be Merged ? 

### ISSUE THREAD

**Issue by Mahesh-Gunda-Maersk** [oauth2-proxy/oauth2-proxy#2169] opened 2023-07-24 09:02 UTC
## Steps to Reproduce (for bugs)

1.  
2.  
3.  
4.  

## Your Environment

- Version used:

**Comment by kvanzuijlen** [comment] 2023-09-05 23:32
@JoelSpeed duplicate of #2170, can be closed

**Closed** 2023-09-06 08:22 UTC
