### ISSUE TITLE
404 page not found, after upgrade to latest oauth2-proxy v6.1.0

### ISSUE THREAD

**Issue by r-kotagudem** [oauth2-proxy/oauth2-proxy#745] opened 2020-08-29 17:04 UTC
Hi @JoelSpeed 

I have been using latest image in oauth2-proxy deployment file. 
After the new release, Im seeing '404 page not found', after login and redirect to backend.
I have used the v6.0.0 in the image which solved the issue.

expected behaviour: redirect to backend application after login.
current behaviour: redirect to backend is not happening instead it shows below

![image](https://user-images.githubusercontent.com/62635671/91642300-da0bb780-ea47-11ea-88e1-2a3112a50b6b.png)

when accessing app url, It shows login page, after entering the credentials and submit, it shows 404 page not found.

below is oauthproxy deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: oauth2-proxy
  name: oauth2-proxy-si
  namespace: myns
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: oauth2-proxy
  template:
    metadata:
      labels:
        k8s-app: oauth2-proxy
    spec:
      containers:
      - args:
        - --provider=oidc
        - --email-domain=*
        - --cookie-domain=.appdomain.com
        - --http-address=0.0.0.0:4180
        - --pass-access-token=true
        - --pass-authorization-header=false
        - --set-authorization-header=true
        - --pass-user-headers=true
        - --set-xauthrequest=true
        - --skip-oidc-discovery=true
        - --login-url=https://idphost:443/oauth2/rest/authorize
        - --insecure-oidc-skip-issuer-verification=true
        - --oidc-issuer-url=https://idphost:443/oauth2
        - --oidc-jwks-url=http://idphost/oauth2/rest/security
        - --redeem-url=http://idphost/oauth2/rest/token
        - --validate-url=http://idphost/oauth2/rest/userinfo
        - --cookie-refresh=1h0m0s
        - --whitelist-domain="idphost"
        - --cookie-httponly=false
        - --cookie-secure=false
        - --standard-logging=true
        - --auth-logging=true
        - --request-logging=true
        - --skip-provider-button=true
        - --upstream=static://200
        - --redis-connection-url=redis://redis-master.default.svc.cluster.local:6379
        - --session-store-type=redis
        env:
        - name: OAUTH2_PROXY_CLIENT_ID
          value: <client id>
        - name: OAUTH2_PROXY_CLIENT_SECRET
          value: <secret>
        - name: OAUTH2_PROXY_COOKIE_SECRET
          value: 
        - name: OAUTH2_PROXY_COOKIE_DOMAIN
          value: .example.com
        image: quay.io/oauth2-proxy/oauth2-proxy:latest
        imagePullPolicy: Always
        name: oauth2-proxy
        ports:
        - containerPort: 4180
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: oauth2-proxy
  name: oauthproxy-service-si
  namespace: myns
spec:
  ports:
  - name: http
    port: 4180
    protocol: TCP
    targetPort: 4180
  selector:
    k8s-app: oauth2-proxy
---

using istio envoy filter, let me know if this file is needed

**Comment by haslersn** [comment] 2020-08-31 04:54
I have the same issue: My oauth2-proxy `v6.1.0` only returns 404 with the following upstream:

```
upstreams = [
    "static://200"
]
```

oauth2-proxy `v6.0.0` returns 200 as intended.

**Comment by JoelSpeed** [comment] 2020-08-31 09:46
To confirm, if post login you access any URL on the oauth2-proxy application, eg `/`, it shows a 404 instead of a 200 as intended? 

We did a large refactor of the upstream handling code during the 6.1.0 release so there could be a bug there, though I was pretty sure I'd tested this out

**Comment by JoelSpeed** [comment] 2020-08-31 10:12
I've verified this is a genuine bug in the conversion logic we have between the external options and the internal configuration, I will open a PR to fix and cherry-pick the fix to make a 6.1.1 release once it is merged

**Closed** 2020-08-31 15:58 UTC
Labels: bug

**Comment by JoelSpeed** [comment] 2020-08-31 16:32
This should be fixed in the v6.1.1 release which has just been published

**Comment by joaopalma5** [comment] 2020-10-16 16:20
@JoelSpeed in docker if you use the variable environment OAUTH2_PROXY_UPSTREAM: "static://200" not works

**Comment by JoelSpeed** [comment] 2020-10-28 20:11
The correct environment variable is with a trailing s: `OAUTH2_PROXY_UPSTREAMS: "static://200"`
