### ISSUE TITLE
Oauth2 redirects to absolute oidc-issuer path (instead of relative), which is not accessible for user

### ISSUE THREAD

**Issue by roey383** [oauth2-proxy/oauth2-proxy#2145] opened 2023-06-25 15:25 UTC
## Expected Behavior

When user goes to http://x.x.x.x/my_app,
Need to be redirected to keycloak authentication page in http://x.x.x.x/auth/realms/my_realm/protocol/openid-connect...
As for keycloak.keycloak is behind firewall (x.x.x.x is the firewall ip).
Expected behavior is for oauth2 proxy to redirect only to relative path in oidc-issuer-url.

for this config:
  extraArgs:
  - '--provider=keycloak-oidc'
  - '--set-xauthrequest=true'
  - '--provider-display-name=Keycloak'
  - '--client-id=some-id'
  - '--client-secret=0j0M6CXUZQDf1zXLbWwyKefKUZ0qU1IE'
  - '--keycloak-group=/testgroup1'
  - '--cookie-secure=false'
  - '--insecure-oidc-skip-issuer-verification=true'
  - '--oidc-issuer-url=http://keycloak.keycloak/auth/realms/my_realm'
  - '--http-address=0.0.0.0:4180'
  - '--insecure-oidc-skip-nonce=true'
  - '--redirect-url=/oauth2-some_id/callback'
  - '--pass-authorization-header=true'
  - '--pass-access-token=true'
  - '--pass-user-headers=true'
  - '--set-authorization-header=true'
  - '--set-xauthrequest=true'
  - '--proxy-prefix=/oauth2-some-id'

## Current Behavior

It redirected to http://keycloak.keycloak/auth/realms/my_realm/protocol/openid-connect...
Meaning, it redirected with full path (as in oidc-issuer-url falg value) and not to relative path.
It uses 'keycloak.keycloak' host and not 'x.x.x.x' host

## Steps to Reproduce (for bugs)

Ingress values for my app:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: '/\$2'
    nginx.ingress.kubernetes.io/auth-url: 'http://\$host/oauth2-some-id/auth'
    nginx.ingress.kubernetes.io/auth-signin: 'http://\$host/oauth2-some-id/start?rd=\$escaped_request_uri'
    nginx.ingress.kubernetes.io/auth-response-headers: 'x-auth-request-user, x-auth-request-email'
  hosts:
    - paths:
        - path: '/my_app(/|\$)(.*)'
          pathType: Prefix

ingress for oauth2 proxy:
spec:
  rules:
  -  http:
      paths:
      -  backend:
          service:
            name: oauth2-proxy-some-id
            port:
              number: 80
        path: '/oauth2-some-id'
        pathType: Prefix

- Version used: oauth2 proxy helm 2.1.7

**Comment by corybolar** [comment] 2023-06-29 23:29
Check the values contained within the .well-known/openid-configuration endpoint for keycloak.

Something like: http://x.x.x.x/auth/realms/my_realm/protocol/openid-connect/.well-known/openid-configuration.

**Comment by roey383** [comment] 2023-06-30 06:22
Hi @corybolar ,
Thank you for the response.

But what should I check there? http://x.x.x.x/auth/realms/my_realm/.well-known/openid-configuration
In those values each endpoint is with host x.x.x.x.

For example:
	"issuer": "http://x.x.x.x/auth/realms/my_realm",
	"authorization_endpoint": "http://x.x.x.x/auth/realms/my_realm/protocol/openid-connect/auth",
	"token_endpoint": "http://x.x.x.x/auth/realms/my_realm/protocol/openid-connect/token",
	"introspection_endpoint": "http://x.x.x.x/auth/realms/my_realm/protocol/openid-connect/token/introspect",
	"userinfo_endpoint": "http://x.x.x.x/auth/realms/my_realm/protocol/openid-connect/userinfo",
	"end_session_endpoint": "http://x.x.x.x/auth/realms/my_realm/protocol/openid-connect/logout",
	"frontchannel_logout_session_supported": true,
	"frontchannel_logout_supported": true,
	"jwks_uri": "http://x.x.x.x/auth/realms/my_realm/protocol/openid-connect/certs",
	"check_session_iframe": "http://x.x.x.x/auth/realms/my_realm/protocol/openid-connect/login-status-iframe.html", 

Thank you

**Comment by roey383** [comment] 2023-07-02 12:49
Thanks. 
The issue was solved by configuring Keycloak with the right "frontend url" (will correct external IP)

**Comment by tuunit** [comment] 2023-08-27 12:07
Hi @roey383 if the problem is resolved please close the issue :)

**Closed** 2023-08-27 18:14 UTC

**Comment by sedghi** [comment] 2024-06-05 20:16
@roey383 what did you end up putting in the frontend url?

**Comment by roey383** [comment] 2024-06-09 07:01
Hi @sedghi ,
I filled the full url:
Http://x.x.x.x/my_app

But since then changed and can only be reached from inside firewall. 
Since it's a bad practice. 

Still searching for a better way to reach also from outside
