### ISSUE TITLE
/oauth2/auth the token expiration time is not taken into account

### ISSUE THREAD

**Issue by mohsek** [oauth2-proxy/oauth2-proxy#2301] opened 2023-10-30 17:02 UTC
the endpoint `/oauth2/auth` doesn't check the expiration date of the token in the session. so when calling the endpoint return always a response 202 if the session exists, but it never checks if the session has expired.
## Expected Behavior
if the session is expired, the getAuthenticatedSession() should return an error instead of 202 
## Current Behavior
/oauth2/auth returns 202 even if the session has expired 
## Possible Solution
use session.isExpired() in getAuthenticatedSession()
- Version used: v7.5.1

**Comment by kvanzuijlen** [comment] 2023-10-30 17:08
Duplicate of #1836

**Closed by kvanzuijlen** 2023-10-30 17:08 UTC

**Comment by mohsek** [comment] 2023-10-30 17:10
tested the pull request but doesn't work for me

**Comment by kvanzuijlen** [comment] 2023-10-30 17:11
@mohsek Please add a comment to #1836
