### ISSUE TITLE
github-org and github-team restriction seems not working

### ISSUE THREAD

**Issue by d02540315** [oauth2-proxy/oauth2-proxy#1586] opened 2022-03-09 22:29 UTC
Hi,

I'm trying to restrict access by GitHub Org and Team, it appears I always get authenticated regardless what I put for github-team. I'm trying to put oauth2-proxy before K8s Dashboard and I'm using Enterprise version of GitHub.

I tried to restrict the access by github-repo, I didn't get it working either. All GitHub users get authenticated regardless he/she has access to the github repo or not. 

Any help would be appreciated.

  _github-repo: "kubernetes-dashboard-qc-access"
  #github-org: "abc"
  #github-team: "Kubernetes-Dashboard-QC-Access"_

**Comment by d02540315** [comment] 2022-03-09 22:35
What I meant for alway gets authenticated - I always cloud see _oauth2_proxy_csrf cookie gets populated.
![image](https://user-images.githubusercontent.com/5162421/157550187-f39f325b-0c57-473a-8969-5bc0bab347e0.png)

**Comment by braunsonm** [comment] 2022-03-11 03:05
Without any information about your configuration it would be very difficult to help. Do you think you've found a bug or are just trying to find help with understanding the configuration? You might have some luck asking other Github oauth2-proxy users on Slack too.

**Comment by d02540315** [comment] 2022-03-11 17:12
Thanks @braunsonm for your response. 

 provider: “github”
  set-authorization-header: “true”
  cookie-domain: “.abc-corp.cloud”
  whitelist-domain: “.abc-corp.cloud”
  login-url: “https://abc.dev/login/oauth/authorize”
  redeem-url: “https://abc.dev/login/oauth/access_token”
  validate-url: “https://abc.dev/api/v3”
  redirect-url: “https://k8s-dashboard.abc-corp.cloud/”
  auth-logging: “true”
  standard-logging: “true”
  request-logging: “true”
  set-authorization-header: “true”
  show-debug-on-error: “true”
  cookie-expire: “2h”
  #github-repo: “kubernetes-dashboard-qc-access”
  pass-access-token: “true”
  pass-authorization-header: “true”
  github-org: “abc”
  github-team: “architecture”
  #session-cookie-minimal: “true”
  #pass-user-headers: “true”
  #set-xauthrequest: “true”

**Comment by JoelSpeed** [comment] 2022-03-12 13:34
Might be worth checking with the helm chart maintainers on the repo itself, there's a different set of folks who maintain that.

Is that config the generated config? I don't see the github configuration in the file

**Comment by braunsonm** [comment] 2022-03-17 00:17
At first glance it looks like you commented out the repo config? 
>#github-repo: “kubernetes-dashboard-qc-access”

Closing for now. Please provide a concise reproduction step if you believe this is a bug

**Closed by braunsonm** 2022-03-17 00:17 UTC
Labels: question

**Comment by cedricve** [comment] 2024-10-03 20:21
interested in this as well!
