### ISSUE TITLE
Azure provider with v7.2.1 and ADAL stop working - Access token validation failure. Invalid audience

### ISSUE THREAD

**Issue by pierluigilenoci** [oauth2-proxy/oauth2-proxy#1505] opened 2022-01-06 16:07 UTC
After the update from `v7.2.0` to `v7.2.1` the integration with the AAD stops working. 
We analyzed the difference between the two versions and we understood our issue is this PR: #1433

The pod produces these loglines:
```bash
[2022/01/06 13:32:29] [internal_util.go:74] token validation request failed: status 401 - {"error":{"code":"InvalidAuthenticationToken","message":"Access token validation failure. Invalid audience.","innerError":{"date":"2022-01-06T13:32:29","request-id":"[REDACTED]","client-request-id":"[REDACTED]"}}}
[2022/01/06 13:32:29] [internal_util.go:69] 401 GET https://graph.microsoft.com/v1.0/me {"error":{"code":"InvalidAuthenticationToken","message":"Access token validation failure. Invalid audience.","innerError":{"date":"2022-01-06T13:32:29","request-id":"[REDACTED]","client-request-id":"[REDACTED]"}}}
10.5.1.44:59808 - [REDACTED] - [REDACTED] [2022/01/06 13:32:29] [AuthFailure] Session validation failed: Session{email:[REDACTED] user: PreferredUsername: token:true id_token:true created:2022-01-06 13:32:29.287771102 +0000 UTC m=+2927.613337671 expires:2022-01-06 14:44:17 +0000 UTC refresh_token:true}
```

We analyzed the code. Here is the code involved:
* https://github.com/oauth2-proxy/oauth2-proxy/blob/master/oauthproxy.go#L757-L762
* https://github.com/oauth2-proxy/oauth2-proxy/blob/master/providers/azure.go#L361-L363
* https://github.com/oauth2-proxy/oauth2-proxy/blob/master/providers/internal_util.go#L69
* https://github.com/oauth2-proxy/oauth2-proxy/blob/master/providers/internal_util.go#L74

Our pod is running in this way:
```
--http-address=0.0.0.0:4180
--metrics-address=0.0.0.0:44180
--azure-tenant=[REDACTED]
--cookie-domain=[REDACTED]
--cookie-expire=1h
--cookie-refresh=59m
--oidc-email-claim=sub
--oidc-issuer-url=https://sts.windows.net/[REDACTED]/
--pass-access-token=true
--pass-user-headers=true
--provider=azure
--resource=6dae42f8-4368-4678-94ff-3960e28e3630
--set-xauthrequest=true
--whitelist-domain=.[REDACTED]
--config=/etc/oauth2_proxy/oauth2_proxy.cfg
```

We use Managed AAD with our AKS clusters.
We configure OAuth2 Proxy to work with ADAL but the request for the validation is made to MSAL.
We presume this problem is strictly connected to #1144 and #1231

## Expected Behavior

We expect that the Azure provider is able to validate the token using the same Graph endpoint version or at least it must be able to work.

## Your Environment

- Version used: AKS 1.21.2

**Comment by pierluigilenoci** [comment] 2022-01-06 16:19
@weinong @NickMeves @JoelSpeed @codablock could you please take a look?

FYI: @stippi2 @ludydoo @LouisStAmour @amgtg @antgamdia @avodaqstephan @RichardTheHouse @kernelcoredump @bailsman

**Comment by pierluigilenoci** [comment] 2022-01-20 12:52
@weinong @NickMeves @JoelSpeed @codablock could you please take a look?

**Comment by pierluigilenoci** [comment] 2022-01-26 16:15
@weinong @NickMeves @JoelSpeed @codablock could someone give me a feedback?

**Comment by codablock** [comment] 2022-01-27 08:22
@pierluigilenoci I can only say that we stopped using oauth2-proxy and Azure. We now use dex as an anti-corruption layer between Azure and oauth2-proxy as it seems to be more stable in regard to Azure. I can not give any advice/feedback on oauth2-proxy + Azure anymore.

**Comment by avodaqstephan** [comment] 2022-01-27 08:36
@pierluigilenoci Sorry for being late to the party. We are using keycloak together with oauth2-proxy. So the actual configuration for Azure is happening in keycloak. We got it running with oauth2-proxy only but we need some additional features which only keycloak was able to provide. 
The FAQ on the oauth2-proxy on how to use the proxy with keycloak worked perfectly fine.

**Comment by pierluigilenoci** [comment] 2022-01-28 08:38
@codablock lucky you. 😞

**Comment by weinong** [comment] 2022-01-29 02:29
Sorry. been very busy. I will circle back next week.

**Comment by pierluigilenoci** [comment] 2022-02-07 08:48
Thank you @weinong. Any news?

**Comment by weinong** [comment] 2022-02-08 04:20
I just got my cluster and oauth-proxy re-configured using older version. everything is working so far. I will try the new version soon!

**Comment by weinong** [comment] 2022-02-09 04:10
the issue is v7.2.1 introduced a check on [ValidateSession()](https://github.com/oauth2-proxy/oauth2-proxy/blob/2c668a52d4dc6fba0b13b1ec3ed5b9b828552a0c/oauthproxy.go#L758) which, I guess, has mostly been failing for Azure provider when oauth2-proxy is used in AKS AAD scenario where the token audience is AKS AAD server app. The reason to fail is [this code](https://github.com/oauth2-proxy/oauth2-proxy/blob/16a9893a19dfe832a1acc72af70b27d0150caa7f/providers/azure.go#L362) that in turns uses the access token issued for `--resource` to query Graph api in [this code](https://github.com/oauth2-proxy/oauth2-proxy/blob/16a9893a19dfe832a1acc72af70b27d0150caa7f/providers/internal_util.go#L59).

I don't understand the logic to call Graph api for `validateToken()` here, though. Don't we just need to verify the token cryptographically and its expiration time?

**Comment by pierluigilenoci** [comment] 2022-02-09 10:03
@weinong you should ask @stippi2 (the author of the PR #1433 used to fix #1396) 
or maybe @JoelSpeed and @NickMeves.

For me, this issue is related to #1144 and #1231.

**Comment by stippi2** [comment] 2022-02-09 10:13
> @weinong you should ask @stippi2 (the author of the PR #1433 used to fix #1396)

Please don't confuse what my PR did. The call to `ValidateSession()` was already in the code. But the return value of that check was ignored, which was clearly not the intention. What my PR exposes is that `ValidateSession()` never worked in the first place for the Azure provider. Please note that the return value of `ValidateSession()` was correctly checked when the session is refreshed. So for the Azure provider, it would have failed at that point at the latest, also before my PR was merged.

**Comment by pierluigilenoci** [comment] 2022-02-09 10:25
@stippi2 I totally agree.

The problem is upstream due to the awful (and therefore notorious) implementation of OIDC by Azure.
Ref: #1144 & #1231

**Comment by weinong** [comment] 2022-02-09 17:26
The fix can be simple: I don't see any need to validate the access token in a session by calling the Graph API. If @JoelSpeed  and @NickMeves agree, I can work on the PR.

@stippi2 is right. We should be validate the session. It's just unfortunate....

**Comment by JoelSpeed** [comment] 2022-02-09 18:25
> I don't see any need to validate the access token in a session by calling the Graph API.

The point is that we should be able to check that the access token is valid, maybe not so much on create or refresh but later down the line if we aren't refreshing, for this, there should be some sort of API that we can access to check the access token is still valid no?

**Comment by weinong** [comment] 2022-02-09 19:06
Access token was never validated with any API, though. This is not in any OAuth spec.
The only validation is:
* is this token signed by the trusted issuer --> verify the signature using issuer's public key from oidc discovery document
* is this token still valid --> check expiration
* is the audience correct --> in this case, check against `--resource`

**Comment by pierluigilenoci** [comment] 2022-02-14 10:55
@weinong any news about this?

**Comment by weinong** [comment] 2022-02-16 02:06
i'm working on the fix and please be patient with me :D

**Comment by D-side** [comment] 2022-03-05 09:00
Hi everyone; I have one additional detail, this issue is not exclusive to Azure, **the same is happening with Nextcloud as well**:

```
 {{CLIENT_IP}} - 6f2713eb-e2f6-40a4-bb9b-0872d05afa3c - - [2022/03/05 08:44:06] {{APP_DOMAIN}} GET - "/oauth2/start?rd=%2F" HTTP/1.1 "Mozilla/5.0 (Android 9; Mobile; rv:97.0) Gecko/97.0 Firefox/97.0" 302 341 0.000
 [2022/03/05 08:44:33] [internal_util.go:74] token validation request failed: status 401 - <?xml version="1.0"?>
 <ocs>
  <meta>
   <status>failure</status>
   <statuscode>997</statuscode>
   <message>Current user is not logged in</message>
  </meta>
  <data/>
 </ocs>
 [2022/03/05 08:44:33] [internal_util.go:69] 401 GET https://{{NEXTCLOUD_DOMAIN}}/ocs/v2.php/cloud/user?format=json?access_token={{ACCESS_TOKEN}}<?xml version="1.0"?>
 <ocs>
  <meta>
   <status>failure</status>
   <statuscode>997</statuscode>
   <message>Current user is not logged in</message>
  </meta>
  <data/>
 </ocs>
 {{CLIENT_IP}} - ee069499-7072-4501-92af-a11ff9cd30be - {{USER_EMAIL}} [2022/03/05 08:44:33] [AuthFailure] Session validation failed: Session{email:{{USER_EMAIL}} user: PreferredUsername: token:true created:2022-03-05 08:44:33.630472165 +0000 UTC m=+51.277725155 expires:2022-03-12 08:44:33.630472165 +0000 UTC m=+604851.277725155}
 {{CLIENT_IP}} - ee069499-7072-4501-92af-a11ff9cd30be - - [2022/03/05 08:44:33] {{APP_DOMAIN}} GET - "/oauth2/callback?state={{STATE}}&code={{CODE}}" HTTP/1.1 "Mozilla/5.0 (Android 9; Mobile; rv:97.0) Gecko/97.0 Firefox/97.0" 403 2785 0.184
```
`{{BLOCKS}}` indicate redacted sensitive details.

From a user's perspective it seems to work okay when it doesn't have a load reverse proxy in front of it, but locks users out with a 403 after a successful login when a reverse proxy is present.

Just like in the original report, 7.2.0 works alright with the same setup, with and without a reverse proxy. So I figured the issue must have been introduced since 7.2.0, and I don't see any obvious candidates other than #1433 — which, unfortunately, seems to indicate that **it is a breaking change** 😢

**Comment by braunsonm** [comment] 2022-03-06 04:37
@D-side please make a separate issue as this doesn't seem related to this particular problem.

**Comment by pierluigilenoci** [comment] 2022-03-06 10:57
@weinong any update on the fix?

**Comment by Beanow** [comment] 2022-04-19 18:51
I think it's also happening with Keycloak, as seen in https://github.com/oauth2-proxy/oauth2-proxy/issues/1599
Looks like, it also had a token validation error that was ignored previously, but now results in authentication failure.

**Comment by pierluigilenoci** [comment] 2022-04-25 10:34
@weinong any update on the fix?

**Comment by pierluigilenoci** [comment] 2022-06-27 06:29
@weinong any update on the fix?

**Comment by pierluigilenoci** [comment] 2022-07-13 08:58
Why closed? @braunsonm could you please reopen it?

**Comment by pierluigilenoci** [comment] 2022-09-12 11:30
@JoelSpeed @braunsonm @weinong this would be a really important feature. Is there anyone who can give it a look?

**Comment by braunsonm** [comment] 2022-09-12 11:44
Isn't this fixed by the PR for reworking the Az provider for v2?

**Comment by pierluigilenoci** [comment] 2022-09-12 11:48
@braunsonm there is PR #1574 but it is still far from finished. 😢

**Comment by braunsonm** [comment] 2022-09-12 11:50
That's what I referenced already had my approval but needs to address Joel's comments.

**Comment by pierluigilenoci** [comment] 2022-09-20 08:52
@JoelSpeed can you please reopen this issue?

**Comment by pierluigilenoci** [comment] 2022-09-20 10:11
@JoelSpeed thank you a lot. 🚀 
If I were kind enough to also take a look at the PR #1574 to close this issue it would be great. ❤️

**Closed** 2022-10-21 17:31 UTC
